### PR TITLE
#492 Method add of DyTasks fail

### PR DESCRIPTION
**Pull request by maxim-kornienko**

### CODE REVIEW

**Comment by davvd** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by davvd** [comment]
@krzyk it's yours,please review

**Comment by krzyk** [comment]
@maxim-kornienko please add a test that recreates the problem from the issue, so we can be sure it solves it

**Comment by maxim-kornienko** [comment]
@krzyk there is already `DyTasksTest` for that, check its `@Ignore`d methods.

**Comment by krzyk** [comment]
@maxim-kornienko but in the #492 bug description there is also
>Remember remove the Ignore annotation od the test addTaskWithAttributes and addTaskWithoutAttributes

**Comment by maxim-kornienko** [comment]
@krzyk done

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@krzyk Thanks so much! Your account was topped up for **18 mins** (transaction ID is `50852808`). +18 added to your rating, at the moment it is: [+3059](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
