### PR TITLE
#481 doc.thindeck.com fails to display the logo

### PR DESCRIPTION
**Pull request by maurezen**
Fixed the picture url and css.

### CODE REVIEW

**Comment by davvd** [comment]
@yegor256 this pull request is for you,please review

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by davvd** [comment]
@yegor256 Much obliged! I've added **17 mins** to your account in payment "000-0017571c"; +17 added to your rating, current score is: [+4793](http://www.netbout.com/b/35008?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
