### PR TITLE
update nginx main script

### LINKED ISSUE #495: Nginx.java:66-72: Let's handle the file *main.conf,...
Puzzle `345-f56694d0` in `src/main/java/com/thindeck/steps/Nginx.java:66-72` has to be resolved: Let's handle the file *main.conf, which should contain the server configuration for a given host. The file name is prefixed by the host name, e.g. the host "www.example.com" will have the file name "www.example.com.main.conf". If the file doesn't exist yet, we should create it and include it in nginx.conf. If it already exists, we should update it. See the Javadoc above or the explanation in https://github.com/yegor256/thindeck/issues/347 for more details.

If you have any technical questions, don't ask me, submit new tickets instead

### PR DESCRIPTION
**Pull request by wb14123**
fix #495

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks, I'll find someone to review it before we merge

**Comment by davvd** [comment]
@krzyk please review,thanks

**Comment by krzyk** [comment]
@cyberone please add few tests for this, it will make easier to decide if it is working correctly for most of the cases

**Comment by cyberone** [comment]
@krzyk did you really mean me? I cannot work with this PR.

**Comment by krzyk** [comment]
@cyberone no,  just a mistake :-)

**Comment by krzyk** [comment]
@wb14123 please add few tests for this, it will make easier to decide if it is working correctly for most of the cases

**Comment by krzyk** [comment]
@wb14123 ping

**Comment by krzyk** [comment]
@wb14123 please close this PR if you are not working on it anymore

**Comment by davvd** [comment]
@krzyk thanks, paid, **20 mins** to your account, payment ID is `51685592`... review comments (c=5) added as a bonus... +20 to your rating, your total score is [+4230](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
