### PR TITLE
Test if get method in DyTasks fails properly - Issue #493

### PR DESCRIPTION
**Pull request by Marczeeee**
Issue #493

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@carlosmiranda review this one, please

**Comment by carlosmiranda** [comment]
@rultor can we merge now?

**Comment by yegor256** [comment]
@Marczeeee maybe we can add a test that confirms this behavior? now it looks like a very small change for a full task

**Comment by Marczeeee** [comment]
@yegor256 The getInvalidTask() test method was accidentally added to PR #499 but it was meant to be the part of this PR. That method was created to confirm the behaviour when invalid id presented.

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@carlosmiranda Thanks so much! Your account was topped up for **16 mins** (transaction ID is `50603721`)... added +16 to your rating, now it is equal to [+2096](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@rultor deploy pls

**Pull request merged**
