### PR TITLE
refactored two similar code blocks into private method

### PR DESCRIPTION
**Pull request by wentwog**

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by davvd** [comment]
@longtimeago review this one,please

**Comment by longtimeago** [comment]
@wentwog Looks good, thanks

**Comment by longtimeago** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@longtimeago **16 mins** sent to your balance (ID `50570736`), many thanks!... +16 to your rating, your total score is [+1215](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
