### PR TITLE
491

### PR DESCRIPTION
**Pull request by wentwog**
added check for null. But left the test as @Ignored cos it fails due to the same reason #492 fails.

### CODE REVIEW

**Comment by davvd** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@longtimeago it's yours,please review

**Comment by longtimeago** [comment]
@wentwog You need to reproduce the issue with test and then fix it

**Comment by wentwog** [comment]
@longtimeago yes, [here](https://github.com/yegor256/thindeck/blob/618352ab6046c91dd0c383064d6d658dd68bf47e/src/test/java/com/thindeck/dynamo/DyTasksTest.java#L84) is the test.
And it was failing with NPE. This is the scope of my ticket. (#491)
And I've fixed this, now the test fails due to the other reason. And this reason is #492.

That's why I think the current ticket is done.
What do you think?

**Comment by longtimeago** [comment]
@wentwog then please add todo to uncomment the test and check it works when #492 is done

**Comment by wentwog** [comment]
@longtimeago done.

**Comment by longtimeago** [comment]
@wentwog todo format is wrong
right for your case is 
```
@todo #491:15min Unignore following test when #492 is finished and check the test passes
```

**Comment by longtimeago** [comment]
@wentwog please, run build with qulice profile enabled before any change in PR

**Comment by wentwog** [comment]
@longtimeago thanks ) Done. 
(Only `mvn clean install -Pqilice` doesn't react on the wrong todo format.)

**Comment by longtimeago** [comment]
it's weird ...

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@longtimeago **21 mins** sent to your balance (ID `50597950`), many thanks!... added +21 to your rating, now it is equal to [+1298](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
