### PR TITLE
#469 Mvn running ImmutabilityTest

### PR DESCRIPTION
**Pull request by maxim-kornienko**

### CODE REVIEW

**Comment by davvd** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by davvd** [comment]
@longtimeago this pull request is for you,please review

**Comment by longtimeago** [comment]
@maxim-kornienko looks good

**Comment by longtimeago** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge this

**Comment by longtimeago** [comment]
@yegor256 please, retry. There was a communication issue

**Comment by longtimeago** [comment]
@yegor256 please, retry. There was a communication issue

**Comment by longtimeago** [comment]
@yegor256 Could you please, retry? There was a communication issue

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@longtimeago I added **20 mins** to your account, many thanks for working with the project!; +20 to your rating, your total score is [+1482](http://www.netbout.com/b/35024?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
