### PR TITLE
#410 Removed puzzle

### PR DESCRIPTION
**Pull request by carlosmiranda**
Was resolved in #517, but the puzzle wasn't removed.

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, someone will review your pull request soon

**Comment by davvd** [comment]
@pinaf review this one, please

**Comment by pinaf** [comment]
@carlosmiranda looks good.

**Comment by pinaf** [comment]
@rultor merge

**Comment by carlosmiranda** [comment]
@rultor merge please

**Comment by pinaf** [comment]
@davvd merged 4 days ago

**Comment by pinaf** [comment]
@davvd merged a week ago :(

**Comment by pinaf** [comment]
@yegor256 any idea why this is taking so long?

**Comment by pinaf** [comment]
@davvd @yegor256 merged 11 days ago =p

**Comment by davvd** [comment]
@pinaf thank you, added **17 mins** to your acc, payment num is `AP-55K26291MC973651Y`. extra minutes for review comments (c=2). +17 to your rating, your total score is [+3182](http://www.netbout.com/b/35128?open=rating)

**Comment by pinaf** [comment]
@davvd thank you.

**Comment by davvd** [comment]
@rultor please deploy

**Comment by davvd** [comment]
> @davvd thank you.

@pinaf no problem :)

**Pull request merged**
