### PR TITLE
#404: implement DyTasks.all() method.

### PR DESCRIPTION
**Pull request by php-coder**

### CODE REVIEW

**Comment by krzyk** [comment]
@php-coder Please add a test case, so we can see that this method works :)

**Comment by php-coder** [comment]
I've already spent all my time to get into this code and write test. And now I don't know what to do, because what you're asking me is to spent more time that won't be payable. :-(

**Comment by krzyk** [comment]
@php-coder In your first sentence you mentioned that you wrote a test, is that right? maybe you didn't added it into the PR? I see only one file changed.

**Comment by php-coder** [comment]
@krzyk Oops, sorry, I've corrected my comment (s/and write test/and don't have time to write test/).

**Comment by krzyk** [comment]
@php-coder It is better to start with a test and then add `TODO` for the actual implementation, I think it shouldn't be hard if you look at the other tests related to Dy* classes.

**Comment by php-coder** [comment]
@krzyk Yes, it's a good idea to start from test, but task's title says about implementation and also because I had only 30 min I' focused on implementation.

>I think it shouldn't be hard if you look at the other tests related to Dy* classes

I agree that it's shouldn't hard but I talked not about complexity but about my own time. (Even in our conversation I'm spending my own time that won't be payable..)

**Comment by krzyk** [comment]
@php-coder Sorry, but you have to take under consideration that sometimes PR you submit are not accepted at first. There are some rules that are mostly enforced by qulice, but others are being enforced by the PR reviewer, like lack of test for a code that is testable, or wrong naming convention for classes/methods.
It all takes time, yours and mine. Sometimes you will do a task in 5 mins and it will be accepted, sometimes it will take 1 hour, next time you will try to foresee that and take it under consideration when doing the task.

**Comment by krzyk** [comment]
@php-coder if this PR is no longer needed please close it

**Comment by davvd** [comment]
@krzyk Thank you, I've added **20 mins** to your account in payment/transaction "`50626023`". +20 added to your rating, at the moment it is: [+2669](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
