### PR TITLE
Unignored addTaskNullAttributes. Test runs.

### PR DESCRIPTION
**Pull request by dpisarenko**

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by davvd** [comment]
@krzyk review this one, please

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by dpisarenko** [comment]
@krzyk Rultor didn't respond, please try again.

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@krzyk thanks, I just added **15 mins** to your account, payment `51273384`. +15 to your rating, your total score is [+3589](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
