### PR TITLE
#471- DyScenario - Step implementation

### PR DESCRIPTION
**Pull request by AlexDag**
please, review this job

### CODE REVIEW

**Comment by davvd** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by davvd** [comment]
@krzyk please review,thanks

**Comment by krzyk** [comment]
@AlexDag `DyScenario` steps should depend on `DyTask` (which creates the scenario), not just a constant list of steps

**Comment by AlexDag** [comment]
@krzyk - please,some details about DyTask, sorry, job descriptiom was very brief-"  #420:30min Implement steps method - example in OnDeploy

**Comment by krzyk** [comment]
@AlexDag I think (but someone will explain it more in #498) that `DyTask` should create scenario from `com.thindeck.scenarios` base on the command that it has. But that's just my assumption.

**Comment by krzyk** [comment]
@AlexDag are you still working on this PR? If not please close it, thanks.

**Comment by davvd** [comment]
@krzyk done, I added **18 mins** in payment `50843215`... added +18 to your rating, now it is equal to [+2914](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
